// ─────────────────────────────────────────────────────────────────────────────
// STG Scorecard — Scoring Engine v3
// Segments mapped directly to STG's 8 Pain-Qualified Segments (PQS)
// Decision tree uses EXCLUSIVE routing — each answer pattern maps to ONE result
// Exit-Minded is NOT the default — it's a specific high-valuation-awareness segment
// ─────────────────────────────────────────────────────────────────────────────

export type Scores = Record<string, number>;

export type Section = {
  id: string;
  phase: number;
  title: string;
  subtitle: string;
  questions: Question[];
};

export type Question = {
  id: string;
  text: string;
  context?: string;
  labels: [string, string];
};

export type SegmentResult = {
  primary: string;
  secondary: string;
  emoji: string;
  color: string;
  tagline: string;
  description: string;
  strengths: string[];
  opportunities: string[];
  insight: string;
  urgency: string;
};

// ─── IDENTITY DETECTION ──────────────────────────────────────────────────────

export type KnownIdentity = {
  isKnown: boolean;
  personName?: string;
  companyName?: string;
  hasAppointment?: boolean;
  appointmentNote?: string;
  exitContext?: string;
};

export function identifyRespondent(email: string, company: string): KnownIdentity {
  const e = email.toLowerCase().trim();
  const c = company.toLowerCase().trim();

  const draperEmailPatterns = ["hdraper@draperconstruction.net","hdraper@draper","homa@draper","houma@draper","wahab"];
  const draperCompanyPatterns = ["draper fence","draper fencing","draper rail","draper construction"];

  const emailMatch   = draperEmailPatterns.some((p) => e.includes(p));
  const companyMatch = draperCompanyPatterns.some((p) => c.includes(p));

  if (emailMatch || companyMatch) {
    return {
      isKnown: true,
      personName: "Homa",
      companyName: "Draper Fence & Rail",
      hasAppointment: true,
      appointmentNote:
        "📅 You have an appointment with our Senior Growth Consultant Rob at 11 AM to discuss next steps on the proposal.",
      exitContext:
        "Based on our prior conversation, we know building toward an eventual exit is part of your longer-term vision — so pay particular attention to the Exit & Valuation Readiness section. The numbers in your full report reflect what a buyer would actually see today vs. what's possible in 18–24 months.",
    };
  }

  return { isKnown: false };
}

// ─── QUESTIONS ────────────────────────────────────────────────────────────────

export const SECTIONS: Section[] = [
  {
    id: "sales-process",
    phase: 1,
    title: "Sales Process",
    subtitle: "How structured & consistent is your selling system?",
    questions: [
      {
        id: "defined-process",
        text: "Do you have a defined, milestone-based sales process your team follows?",
        context: "From first contact to signed contract — is it documented and repeatable?",
        labels: ["No process", "Fully defined"],
      },
      {
        id: "contact-speed",
        text: "Do you contact new leads within 5 minutes or less?",
        context: "Speed-to-lead is the single highest-ROI operational change a contractor can make.",
        labels: ["Rarely", "Always"],
      },
      {
        id: "onspot-estimates",
        text: "What % of estimates do you deliver on-the-spot during the first visit?",
        context: "On-spot estimates close at 2–3× the rate of follow-up quotes.",
        labels: ["Very few", "Most of them"],
      },
      {
        id: "close-tracking",
        text: "Are you actively tracking your close rate by salesperson?",
        context: "You can't improve what you don't measure.",
        labels: ["Not tracking", "Full visibility"],
      },
    ],
  },
  {
    id: "team-performance",
    phase: 1,
    title: "Team Performance",
    subtitle: "How well is your team generating & converting business independently?",
    questions: [
      {
        id: "self-generated",
        text: "What % of business is self-generated by your reps (vs. inbound leads you hand them)?",
        context: "Proactive reps = predictable pipeline. Inbound-only = revenue volatility.",
        labels: ["All inbound", "Mostly self-gen"],
      },
      {
        id: "owner-selling",
        text: "How much of your company's revenue requires YOUR direct involvement to close?",
        context: "Be honest — this is the single number that determines your growth ceiling and exit valuation.",
        labels: ["I close most deals", "Team closes without me"],
      },
      {
        id: "addons",
        text: "What % of your orders include add-ons, upgrades, or premium options?",
        context: "50%+ of jobs should include at least one upgrade. This is pure margin with no extra lead cost.",
        labels: ["Rarely / Never", "Most jobs"],
      },
    ],
  },
  {
    id: "people-systems",
    phase: 2,
    title: "People & Systems",
    subtitle: "How well do you hire, onboard, and retain salespeople?",
    questions: [
      {
        id: "hiring-process",
        text: "Do you have a structured hiring process with defined criteria and pre-screening?",
        context: "A-players evaluate YOU before they apply. A structured hiring process attracts better candidates.",
        labels: ["No real process", "Fully structured"],
      },
      {
        id: "onboarding",
        text: "Do you have a documented onboarding playbook and 30/60/90-day ramp schedule?",
        context: "70% of reps fail in 6 months — almost always because of zero onboarding structure, not talent.",
        labels: ["Sink or swim", "Full playbook"],
      },
      {
        id: "rep-retention",
        text: "How long do your salespeople typically stay before leaving or being let go?",
        context: "Industry benchmark: reps who survive 12+ months generate 3× the revenue of those who churn.",
        labels: ["Under 6 months", "12+ months typically"],
      },
      {
        id: "employment-agreement",
        text: "Do you have a formal Sales Role Agreement covering compensation, expectations, and territory?",
        context: "Handshake deals create ambiguity that causes the best reps to leave.",
        labels: ["Handshake deal", "Formal agreement"],
      },
    ],
  },
  {
    id: "coaching-accountability",
    phase: 2,
    title: "Coaching & Accountability",
    subtitle: "How consistently does your team train, practice, and get managed?",
    questions: [
      {
        id: "ride-alongs",
        text: "Do you or your sales manager conduct weekly ride-alongs or recorded call reviews with reps?",
        context: "The fastest way to close skill gaps is live observation — not more training material.",
        labels: ["Never", "Every week"],
      },
      {
        id: "role-play",
        text: "Does your team role-play sales scenarios and objection handling at least weekly?",
        context: "Elite performers practice more than average ones — not less. Reps practice on prospects otherwise.",
        labels: ["Never", "Weekly"],
      },
      {
        id: "pipeline-followup",
        text: "Does your team follow up with every open quote at least once per week until closed or dead?",
        context: "80% of sales require 5+ follow-ups. The average contractor rep stops at 1–2.",
        labels: ["Inconsistent", "Always, systematically"],
      },
      {
        id: "kpis",
        text: "Do you review KPIs (close rate, avg ticket, follow-up rate) with your team on a weekly basis?",
        context: "What gets measured gets managed. Weekly visibility is non-negotiable for improvement.",
        labels: ["Not measuring", "Weekly dashboard review"],
      },
    ],
  },
  {
    id: "valuation-readiness",
    phase: 3,
    title: "Exit & Valuation Readiness",
    subtitle: "How transferable and scalable is your sales operation to a future buyer or operator?",
    questions: [
      {
        id: "referral-program",
        text: "Do you have a formal referral program your team actively promotes on every job?",
        context: "Referral revenue closes at 3× the rate of cold leads and is the most defensible revenue a buyer sees.",
        labels: ["No program", "Active, systematic program"],
      },
      {
        id: "owner-dependency",
        text: "How owner-independent is your sales operation on a daily basis?",
        context: "Can your team generate leads, run estimates, and close deals without you in the room?",
        labels: ["I'm involved in everything", "Runs without me"],
      },
      {
        id: "documented-playbook",
        text: "Is your complete sales process documented in a written playbook any new hire could follow?",
        context: "Buyers pay a 2×+ multiple premium for businesses where the process outlives the owner.",
        labels: ["In my head only", "Fully documented"],
      },
      {
        id: "revenue-predictability",
        text: "How predictable is your revenue month-to-month?",
        context: "Revenue swinging 40%+ monthly is a valuation killer — PE buyers price it as risk.",
        labels: ["Very volatile (40%+ swings)", "Very predictable (within 10%)"],
      },
    ],
  },
];

export const TOTAL_QUESTIONS = SECTIONS.reduce((a, s) => a + s.questions.length, 0);
export const MAX_SCORE = TOTAL_QUESTIONS * 5;

// ─── DIMENSION SCORES ────────────────────────────────────────────────────────

export type Dimensions = {
  process: number;
  team: number;
  people: number;
  coaching: number;
  valuation: number;
  overall: number;
};

export function computeDimensions(scores: Scores): Dimensions {
  const pct = (keys: string[]) => {
    const total = keys.reduce((a, k) => a + (scores[k] ?? 0), 0);
    return Math.round((total / (keys.length * 5)) * 100);
  };

  const process   = pct(["defined-process", "contact-speed", "onspot-estimates", "close-tracking"]);
  const team      = pct(["self-generated", "owner-selling", "addons"]);
  const people    = pct(["hiring-process", "onboarding", "rep-retention", "employment-agreement"]);
  const coaching  = pct(["ride-alongs", "role-play", "pipeline-followup", "kpis"]);
  const valuation = pct(["referral-program", "owner-dependency", "documented-playbook", "revenue-predictability"]);

  // Weighted composite — process & team weighted highest (core STG product)
  const overall = Math.round(
    process   * 0.25 +
    team      * 0.22 +
    people    * 0.18 +
    coaching  * 0.18 +
    valuation * 0.17
  );

  return { process, team, people, coaching, valuation, overall };
}

// ─── SEGMENT CLASSIFICATION ENGINE ───────────────────────────────────────────
//
// ROUTING LOGIC (exclusive, priority-ordered):
//
// 1. Foundation Builder  → overall < 30 (everything is broken, start here)
// 2. Exhausted Scaler    → owner-selling ≤ 2 AND process < 50 (owner IS the sales team)
// 3. Attrition-Plagued   → rep-retention ≤ 2 AND people < 45 (revolving door)
// 4. Growth-Stalled      → overall 35–60, no dominant weakness (hitting ceiling)
// 5. Exit-Minded         → valuation < 40 AND overall ≥ 50 (decent ops, exit gap specifically)
// 6. Scale-Ready         → overall ≥ 65 (optimizing, not rebuilding)
//
// Exit-Minded ONLY fires when overall is reasonably strong (≥50)
// This means someone who answered well on process/team/people but weak on valuation
// — that's the actual exit-minded profile, not "everyone who scored low"

export function classifySegment(scores: Scores): SegmentResult {
  const d = computeDimensions(scores);

  const ownerSelling  = scores["owner-selling"]       ?? 0;
  const repRetention  = scores["rep-retention"]       ?? 0;
  const onboarding    = scores["onboarding"]          ?? 0;
  const definedProc   = scores["defined-process"]     ?? 0;
  const closeTracking = scores["close-tracking"]      ?? 0;
  const ownerDep      = scores["owner-dependency"]    ?? 0;
  const playbook      = scores["documented-playbook"] ?? 0;
  const revPred       = scores["revenue-predictability"] ?? 0;
  const rideAlongs    = scores["ride-alongs"]         ?? 0;

  // ── 1. FOUNDATION BUILDER ─────────────────────────────────────────────────
  // Catches: overall < 30 — nothing is in place yet
  if (d.overall < 30) {
    return {
      primary: "Foundation Builder",
      secondary: "Sales Infrastructure Gap",
      emoji: "🔧",
      color: "#f97316",
      tagline: "Every high-performing sales team started exactly here — now it's your turn.",
      description:
        "Your scores reflect a sales operation that's running on instinct, relationships, and hustle — not systems. That's how most contractors start, and it works until it doesn't. The good news: everything on this report is learnable, buildable, and proven to work in your industry.",
      strengths: buildStrengths(d, scores),
      opportunities: [
        "Define your sales process end-to-end before adding more people — without it, every hire fails the same way",
        "Start measuring close rate this week — even a simple spreadsheet changes behavior overnight",
        "Build a 5-step follow-up sequence so no quote goes dead without at least 3 contacts",
        "Create your first written onboarding guide before your next hire arrives",
        "Track lead response time — the contractor who responds first wins 60%+ of contested jobs",
      ],
      insight:
        "The single biggest lever in the first 90 days isn't training — it's measurement. Contractors who start tracking close rate, follow-up rate, and lead response time see improvement within 30 days purely from behavioral change. You can't improve what you're not watching.",
      urgency:
        "Every month without a defined process is a month your team improvises differently on every lead. That inconsistency costs deals you'll never know you lost. The contractors building systems now are creating a compounding advantage over every competitor still running on gut.",
    };
  }

  // ── 2. EXHAUSTED SCALER ───────────────────────────────────────────────────
  // Catches: owner doing most of the selling + process not formalized
  // This is STG's #1 segment (score 94/100 in their PQS)
  if (ownerSelling <= 2 && d.process < 55) {
    const noData    = closeTracking <= 2;
    const noProcess = definedProc   <= 2;

    const flavor = noProcess ? "no-process" : noData ? "no-data" : "default";

    const descriptions: Record<string, string> = {
      "no-process":
        "You are your company's best salesperson. Every rep you hire underperforms by comparison — and you know it. So you jump back in, you close the deals, and the revenue holds. But the business can only grow as fast as you can personally show up, quote, and follow up. That ceiling is real, and it's closer than you think.",
      "no-data":
        "You're closing deals at a rate your reps can't touch — but you have no documented process to transfer why. When a prospect asks for YOU specifically, that's not a compliment. It's a signal that your team hasn't been able to replicate what you do. You can fix that.",
      "default":
        "Your instincts close deals your reps can't replicate yet. You've built something real — now the question is whether it can grow without requiring your personal presence on every deal. That transition from owner-seller to owner-leader is the most valuable thing you can build right now.",
    };

    return {
      primary: "Exhausted Scaler",
      secondary: "Owner Dependency",
      emoji: "⚡",
      color: "#FF6B35",
      tagline: "You ARE the sales team. That's the ceiling.",
      description: descriptions[flavor],
      strengths: buildStrengths(d, scores),
      opportunities: [
        "Codify YOUR selling approach — record yourself on 3 estimate calls and extract the pattern your reps can follow",
        "Set a 90-day goal: your next rep closes their first solo deal without you in the room",
        "Start measuring close rate by rep separately from yours — make the gap visible so you can close it",
        "Build a structured 5-touch follow-up cadence that works when you're NOT the one following up",
        "Create accountability check-ins so reps know their numbers are being watched weekly, not quarterly",
      ],
      insight:
        "STG's Baseline Selling methodology was specifically designed for this moment: transferring what a top-performing owner does instinctively — the questions, the timing, the objection handling — into a trainable system any rep can follow. Contractors who make this transition typically see their best rep hit 60–70% of their owner's close rate within 90 days.",
      urgency:
        "Every year you stay in this pattern is another year of 60+ hour weeks, missed deals when you're stretched thin, and a business that's worth a fraction of what it could be at exit. The cost of doing nothing here — in lost deals, in owner time, in future valuation — is typically $200K–$400K per year.",
    };
  }

  // ── 3. ATTRITION-PLAGUED ─────────────────────────────────────────────────
  // Catches: low rep retention + weak people infrastructure
  if (repRetention <= 2 && d.people < 45) {
    const noOnboarding = onboarding <= 2;
    const noRideAlongs = rideAlongs <= 2;

    const flavor = noOnboarding ? "no-onboarding" : noRideAlongs ? "no-coaching" : "default";

    const descriptions: Record<string, string> = {
      "no-onboarding":
        "Your hiring and firing cycle is expensive in ways that don't show up clearly in the books. You hire, they struggle for 3–4 months, they leave — and you're back to square one. The rep wasn't usually the problem. The onboarding was. 70% of first-year rep failures trace directly to no structure in the ramp period.",
      "no-coaching":
        "You have reps in the field learning on real prospects instead of in structured practice. Every mistake they make costs you a deal. Every objection they fumble could have been practiced. The fastest way to build sales skill isn't more experience — it's deliberate repetition in a safe environment.",
      "default":
        "Your team isn't sticking. Good people come in with potential and leave before they peak. The pattern almost always traces to the same root: no formal onboarding, no coaching structure, no clear path for a rep to see what success looks like in the first 90 days.",
    };

    return {
      primary: "Attrition-Plagued",
      secondary: "People Infrastructure Gap",
      emoji: "🔄",
      color: "#f97316",
      tagline: "Great hires leave great companies without great systems.",
      description: descriptions[flavor],
      strengths: buildStrengths(d, scores),
      opportunities: [
        "Build a 30/60/90-day onboarding track — this single change reduces first-year turnover by 40–60%",
        "Add a behavioral screening step to your hiring process — coachability matters more than experience",
        "Implement weekly ride-alongs or recorded call reviews so coaching happens systematically, not reactively",
        "Create a formal Sales Role Agreement with written expectations so day-one clarity replaces later surprises",
        "Run monthly role-plays on your top 3 most common objections — practice in safe environments, not on live prospects",
      ],
      insight:
        "STG's data across 1,000+ contractor clients shows that structured onboarding cuts rep ramp time from 4–6 months to 6–8 weeks. That means 3–4 more months of productive selling per hire, per year. At $375K average annual revenue per trained rep, that difference compounds fast.",
      urgency:
        "One unexpected departure from your current team resets the revenue clock. The recruiting cost, ramp time, and lost pipeline from a single unplanned exit typically runs $40K–$80K in specialty contracting. Building the infrastructure before that happens is always cheaper than rebuilding after.",
    };
  }

  // ── 4. GROWTH-STALLED ─────────────────────────────────────────────────────
  // Catches: mid-range scores, not dominated by one specific gap
  // Revenue exists, team exists — but ceiling has been hit
  if (d.overall >= 30 && d.overall < 60) {
    const lowestDim = getLowestDimension(d);

    const bottleneckMap: Record<string, string> = {
      process:
        "Your process score is the constraint. You have people and some accountability — but the selling steps aren't standardized enough to deliver consistent results across every rep every week. Inconsistent process = inconsistent revenue.",
      team:
        "Your team's self-generation and close performance is the gap. Revenue growth is downstream of lead volume — but lead volume is downstream of how proactively your reps create their own pipeline. That proactivity doesn't happen without training and accountability.",
      people:
        "The people infrastructure is holding you back. You can have great process and coaching — but if reps keep churning before they peak, none of it compounds. One good structural hire or onboarding improvement unlocks disproportionate performance gains.",
      coaching:
        "The accountability and coaching cadence is the missing multiplier. Skills plateau when there's no practice structure and no weekly visibility into performance gaps. The same rep who stalls with no coaching often becomes a top performer with 90 days of structured development.",
      valuation:
        "Your operational scores are reasonable — the valuation infrastructure is the lagging indicator. A buyer looking at your business today would see revenue but not a system. That distinction is worth real dollars when it's time to negotiate.",
    };

    return {
      primary: "Growth-Stalled",
      secondary: "Revenue Ceiling",
      emoji: "📈",
      color: "#eab308",
      tagline: "You've outgrown hustle as a strategy. Systems are next.",
      description:
        "Revenue is real. You've built a team and they're producing something. But growth has plateaued — and the fix isn't working harder or hiring another rep before fixing the system they'd be walking into. The ceiling you're hitting is almost always infrastructure, not effort.",
      strengths: buildStrengths(d, scores),
      opportunities: buildOpportunitiesFromLowest(d, scores),
      insight: bottleneckMap[lowestDim],
      urgency:
        "The contractors who break through the $3–5M ceiling aren't outworking the ones who don't — they're out-systematizing them. The window to do that before your market gets more competitive is shorter than it feels. Businesses that install the infrastructure now compound into the ones setting the ceiling for everyone else.",
    };
  }

  // ── 5. EXIT-MINDED ────────────────────────────────────────────────────────
  // ONLY fires when overall is decent (≥60) but valuation specifically is weak
  // This is someone with solid operations who hasn't built for transferability
  if (d.overall >= 60 && d.valuation < 45) {
    const noPlaybook = playbook    <= 2;
    const noOwnerDep = ownerDep    <= 2;
    const volatileRev = revPred    <= 2;

    const primaryGap = noOwnerDep ? "owner-dependency"
      : noPlaybook   ? "undocumented"
      : volatileRev  ? "volatile"
      : "default";

    const descriptions: Record<string, string> = {
      "owner-dependency":
        "Your operations are solid — process, team, and coaching are working. The gap is that buyers can't see the business running without you. The revenue exists because you're in it, not because the system generates it independently. That distinction is worth 1.5–3× in exit multiple.",
      "undocumented":
        "You have a real, functioning sales operation — but it lives in the heads of your people, not in documentation a buyer can review and trust. Undocumented processes signal risk to acquirers. The same business with a written playbook commands a meaningfully higher multiple.",
      "volatile":
        "Strong operations, but revenue volatility is showing up in your numbers. PE and strategic buyers look at trailing 12-month variability before making offers. Tightening that variance — even by 20% — can shift the multiple they're willing to pay.",
      "default":
        "Your business is performing well operationally. The gap is the documentation, systems, and owner-independence a buyer needs to feel comfortable paying full price. Those things take 12–18 months to build and demonstrate — which means the work starts now.",
    };

    return {
      primary: "Exit-Minded",
      secondary: "Valuation Gap",
      emoji: "🎯",
      color: "#00D9FF",
      tagline: "Strong business. The gap is what a buyer sees vs. what you've built.",
      description: descriptions[primaryGap],
      strengths: buildStrengths(d, scores),
      opportunities: [
        "Document your complete sales process — this is the single highest-impact thing you can do for valuation",
        "Reduce owner involvement in the sales cycle step by step — each decision you remove adds to the multiple",
        "Build a referral program to create a second pipeline channel buyers see as defensible and recurring",
        "Install 12-month KPI trend reporting — buyers pay for trajectory, not snapshots",
        "Tighten revenue variance — predictable monthly revenue gets priced at 6–9× vs. volatile at 3–5×",
      ],
      insight:
        "Specialty contractors with documented, owner-independent sales systems sell for 6.2–9× EBITDA. Owner-dependent businesses typically price at 4–5×. On a $2M revenue business at 10% EBITDA, that gap is $240K–$800K in exit value. On a $5M revenue business, it's $600K–$2M.",
      urgency:
        "Buyers want to see 12–18 months of owner-independent performance before they sign. That clock starts the day you start building the infrastructure — not the day you decide to sell. Every month you wait is a month that clock doesn't start.",
    };
  }

  // ── 6. SCALE-READY ────────────────────────────────────────────────────────
  // Strong across the board — optimizing, not building from scratch
  if (d.overall >= 60) {
    const nearExit = d.valuation >= 60;
    const lowestDim = getLowestDimension(d);

    return {
      primary: "Scale-Ready",
      secondary: nearExit ? "Exit Optimization" : "Performance Optimization",
      emoji: "🚀",
      color: "#22c55e",
      tagline: nearExit
        ? "Strong foundation. Time to maximize the multiple."
        : "Strong foundation. Time to compound what's working.",
      description:
        "You're running a sales operation that's ahead of most contractors in your revenue range. The infrastructure is there — the opportunity now is compounding what's working, filling the specific gaps that are still leaving performance on the table, and making sure the machine is documented well enough that it performs with or without you.",
      strengths: buildStrengths(d, scores),
      opportunities: buildOpportunitiesFromLowest(d, scores),
      insight:
        "At this maturity level, a 5% improvement in close rate or $2K increase in average ticket adds disproportionate bottom-line impact — and both compound directly into exit valuation. The gap between a good exit and a great exit is usually found in 2–3 specific metrics that aren't being optimized yet.",
      urgency:
        "The businesses that sustain elite performance are the ones that treat optimization as a permanent discipline, not a one-time project. The compounding advantage of incremental improvement at this stage is significant — and it's harder for competitors to catch up to a moving target.",
    };
  }

  // ── FALLBACK (shouldn't normally hit) ────────────────────────────────────
  return {
    primary: "Foundation Builder",
    secondary: "Sales Infrastructure Gap",
    emoji: "🔧",
    color: "#eab308",
    tagline: "Every elite sales operation started exactly here.",
    description:
      "Your scores suggest a sales operation in early stages — which means the upside is enormous. The contractors who systematize early get a permanent competitive advantage over those who wait.",
    strengths: buildStrengths(d, scores),
    opportunities: [
      "Define your sales process end-to-end before adding more people",
      "Start measuring close rate and lead response time this week",
      "Build a simple onboarding guide for your first or next hire",
      "Create a follow-up cadence and make it non-negotiable",
    ],
    insight:
      "The ROI on installing sales infrastructure early — before you're dependent on it — is 10× higher than fixing it under pressure.",
    urgency:
      "Most contractors wait until they're forced to build systems. The ones who do it proactively are the ones who dominate their market.",
  };
}

// ─── DYNAMIC STRENGTHS ───────────────────────────────────────────────────────

function buildStrengths(d: Dimensions, scores: Scores): string[] {
  const s: string[] = [];

  if (d.process   >= 60) s.push("Your sales process has real structure — that's ahead of most contractors at your revenue level");
  if (d.team      >= 60) s.push("Your team generates business proactively and doesn't just wait for inbound leads");
  if (d.people    >= 60) s.push("Your hiring and onboarding infrastructure gives new reps a real chance to succeed");
  if (d.coaching  >= 60) s.push("Regular coaching and accountability cadences are in place — that's a genuine competitive differentiator");
  if (d.valuation >= 60) s.push("Your valuation readiness is strong — the business has the bones buyers want to see");

  if ((scores["owner-dependency"]    ?? 0) >= 4) s.push("Your sales operation can run without you in the room — that alone is worth a premium multiple");
  if ((scores["referral-program"]    ?? 0) >= 4) s.push("Active referral program generating high-margin, predictable pipeline");
  if ((scores["onspot-estimates"]    ?? 0) >= 4) s.push("On-spot estimates close 2–3× faster — you're already doing this consistently");
  if ((scores["contact-speed"]       ?? 0) >= 4) s.push("Fast lead response time puts you ahead of 60% of competitors on contested leads");
  if ((scores["documented-playbook"] ?? 0) >= 4) s.push("Documented sales playbook — any new hire can follow your system from day one");
  if ((scores["pipeline-followup"]   ?? 0) >= 4) s.push("Systematic follow-up discipline is one of the highest-ROI habits your team has built");

  // Floor — always show at least 2 strengths
  if (s.length === 0) {
    s.push("You're asking the right questions — most contractors never audit their sales operation at all");
    s.push("Taking this assessment is a deliberate act. Most of your competitors will never do this.");
  } else if (s.length === 1) {
    s.push("You've built a real business with real customers — that foundation is what systems and training plug into");
  }

  return s.slice(0, 5);
}

// ─── LOWEST DIMENSION FINDER ─────────────────────────────────────────────────

function getLowestDimension(d: Dimensions): keyof Omit<Dimensions, "overall"> {
  const dims = {
    process:   d.process,
    team:      d.team,
    people:    d.people,
    coaching:  d.coaching,
    valuation: d.valuation,
  };
  return Object.entries(dims).sort((a, b) => a[1] - b[1])[0][0] as keyof typeof dims;
}

// ─── OPPORTUNITIES FROM LOWEST DIMENSION ─────────────────────────────────────

function buildOpportunitiesFromLowest(d: Dimensions, scores: Scores): string[] {
  const lowest = getLowestDimension(d);

  const opps: Record<string, string[]> = {
    process: [
      "Standardize your 5-step sales process so every rep runs the same play on every lead",
      "Install a lead response SLA — first contact within 5 minutes wins 40% more contested jobs",
      "Build an on-spot estimate template that closes same-day instead of following up 3 times",
      "Create a weekly close-rate review — just sharing the number with the team moves it",
    ],
    team: [
      "Launch a neighborhood canvassing system — every installed job should seed 3–5 conversations",
      "Set self-gen expectations in every rep role — inbound-only reps are a revenue liability",
      "Add a structured upgrade ask to every estimate — 50%+ of jobs should include at least one add-on",
      "Create a formal referral ask at job completion — referrals close at 3× the rate of cold leads",
    ],
    people: [
      "Build a 30/60/90-day onboarding track — this single change cuts first-year turnover by 40–60%",
      "Add behavioral screening to your hiring process — coachability beats experience every time",
      "Create a Sales Role Agreement before the next hire — written expectations prevent most early departures",
      "Build a hiring process that showcases your company as a professional operation worth joining",
    ],
    coaching: [
      "Launch weekly 30-min ride-alongs or recorded call reviews — live observation beats all other coaching",
      "Run monthly role-plays on your top 3 objections — reps who practice in safe environments win more in the field",
      "Build a pipeline review cadence so every open quote is visible and nothing stalls without a reason",
      "Create a KPI dashboard — close rate, lead response time, follow-up rate — reviewed every week without exception",
    ],
    valuation: [
      "Document your complete sales process — this is the #1 thing buyers review in due diligence",
      "Build a referral program to show buyers a second, defensible pipeline channel",
      "Reduce owner involvement in sales decisions — every step you remove adds to the multiple",
      "Track and present 12+ months of KPI trends — buyers pay for trajectory, not snapshots",
    ],
  };

  return opps[lowest] ?? opps["process"];
}

// ─── TEASER TEXT ENGINE ───────────────────────────────────────────────────────
// Answer-driven. 8+ variants. Specific enough to feel accurate.

export function getTeaserText(scores: Scores): string {
  const d = computeDimensions(scores);

  const ownerSelling  = scores["owner-selling"]        ?? 0;
  const repRetention  = scores["rep-retention"]        ?? 0;
  const closeTracking = scores["close-tracking"]       ?? 0;
  const onboarding    = scores["onboarding"]           ?? 0;
  const ownerDep      = scores["owner-dependency"]     ?? 0;
  const playbook      = scores["documented-playbook"]  ?? 0;
  const revPred       = scores["revenue-predictability"] ?? 0;
  const rideAlongs    = scores["ride-alongs"]          ?? 0;
  const followup      = scores["pipeline-followup"]    ?? 0;

  if (d.overall < 30) {
    return "Your scores across all 5 dimensions are in the early-stage range — which means the opportunity here is enormous. Your full report identifies the 3 highest-leverage starting points based specifically on your answers, ranked by ROI.";
  }

  if (ownerSelling <= 2 && d.process < 55) {
    return `Your owner-selling and process scores are flagging the pattern we see most often in high-performing contractor owners: you're the ceiling. The business performs because you perform — and your full report quantifies exactly what that's costing you in time, revenue, and eventual exit value.`;
  }

  if (repRetention <= 2 && onboarding <= 2) {
    return `Your people scores reveal a revolving-door pattern — good people coming in, not staying long enough to peak. The data on this is clear: 70% of rep failures are onboarding failures, not talent failures. Your full report shows exactly where the structure breaks down.`;
  }

  if (closeTracking <= 2 && followup <= 2) {
    return `Two of your scores are flagging a blind spot: you're running the business without visibility into close rate or follow-up discipline. Your full report shows what that invisible gap is likely costing you in monthly revenue — the number usually surprises people.`;
  }

  if (ownerDep <= 2 && playbook <= 2 && d.overall >= 50) {
    return `Your operational scores are solid — process, team, and coaching are working. The gap your full report identifies is in valuation readiness: the business performs well, but it performs because of YOU, not because of a documented system. That distinction is worth real money at exit.`;
  }

  if (revPred <= 2) {
    return `Your revenue predictability score is flagging volatility that sophisticated buyers price as risk. Even if annual revenue looks strong, month-to-month swings reduce EBITDA multiples by 1–2× in most specialty contractor transactions. Your full report shows the fix.`;
  }

  if (rideAlongs <= 2 && d.coaching < 40) {
    return `Your coaching scores suggest your reps are practicing on live prospects instead of in structured environments. That's where deals are being lost invisibly — not from lack of effort, but from lack of deliberate skill-building. Your full report identifies the highest-leverage intervention.`;
  }

  if (d.overall >= 65) {
    return `Your overall score puts you in the top 20% of contractors who've taken this assessment. Your full report identifies the specific 2–3 gaps between where you are and peak performance — at this stage, it's optimization, not rebuilding.`;
  }

  return `Your scorecard reveals a specific pattern across 5 dimensions — with a clear primary gap between your current trajectory and where the highest-performing contractors in your space are operating. Your full report shows exactly where that gap is and what each piece is worth to fix.`;
}

// ─── HELPERS ─────────────────────────────────────────────────────────────────

export function scoreColor(pct: number): string {
  if (pct >= 80) return "#22c55e";
  if (pct >= 60) return "#00D9FF";
  if (pct >= 40) return "#eab308";
  if (pct >= 20) return "#f97316";
  return "#ef4444";
}

export function scoreLabel(pct: number): string {
  if (pct >= 80) return "Strong";
  if (pct >= 60) return "Developing";
  if (pct >= 40) return "Needs Work";
  if (pct >= 20) return "At Risk";
  return "Critical Gap";
}

export function formatPhone(value: string): string {
  const digits = value.replace(/\D/g, "").substring(0, 10);
  if (digits.length === 0) return "";
  if (digits.length <= 3) return `(${digits}`;
  if (digits.length <= 6) return `(${digits.slice(0, 3)}) ${digits.slice(3)}`;
  return `(${digits.slice(0, 3)}) ${digits.slice(3, 6)}-${digits.slice(6)}`;
}

export function isValidPhone(phone: string): boolean {
  const digits = phone.replace(/\D/g, "");
  if (digits.length !== 10) return false;
  if (digits[0] === "0" || digits[0] === "1") return false;
  if (/^(\d)\1{9}$/.test(digits)) return false;
  const fakes = ["1234567890","0987654321","1231231234","1111111111",
    "2222222222","3333333333","4444444444","5555555555",
    "6666666666","7777777777","8888888888","9999999999","0000000000"];
  return !fakes.includes(digits);
}

export function isValidEmail(email: string): boolean {
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(email)) return false;
  const fakeDomains = ["test.com","example.com","fake.com","temp.com",
    "noreply.com","mailinator.com","guerrillamail.com","throwaway.com","yopmail.com"];
  const domain = email.split("@")[1]?.toLowerCase();
  return !(domain && fakeDomains.includes(domain));
}
