// ─────────────────────────────────────────────────────────────────────────────
// STG Scorecard — Pure Answer-Driven Scoring Engine
// Every result is derived 100% from the respondent's answers.
// Identity detection is a separate layer (see identifyRespondent()).
// ─────────────────────────────────────────────────────────────────────────────

export type Scores = Record<string, number>;

export type Section = {
  id: string;
  phase: number;
  title: string;
  subtitle: string;
  questions: Question[];
};

export type Question = {
  id: string;
  text: string;
  context?: string;
  labels: [string, string];
};

export type SegmentResult = {
  primary: string;
  secondary: string;
  emoji: string;
  color: string;
  tagline: string;
  description: string;
  strengths: string[];
  opportunities: string[];
  insight: string;
  urgency: string;
  // Rob's-notes overlay — only populated when identity is confirmed
  robNotes?: string;
};

// ─── IDENTITY DETECTION ──────────────────────────────────────────────────────
// Returns true if the email or company string matches known Draper Fence identity.
// Fuzzy: handles typos, capitalization, partial matches.

export type KnownIdentity = {
  isKnown: boolean;
  personName?: string;
  companyName?: string;
  hasAppointment?: boolean;
  appointmentNote?: string;
  exitContext?: string;
};

export function identifyRespondent(email: string, company: string): KnownIdentity {
  const e = email.toLowerCase().trim();
  const c = company.toLowerCase().trim();

  const draperEmailPatterns = [
    "hdraper@draperconstruction.net",
    "hdraper@draper",
    "homa@draper",
    "houma@draper",
    "wahab",
  ];
  const draperCompanyPatterns = [
    "draper fence",
    "draper fencing",
    "draper rail",
    "draper construction",
    "draper f",
  ];

  const emailMatch = draperEmailPatterns.some((p) => e.includes(p));
  const companyMatch = draperCompanyPatterns.some((p) => c.includes(p));

  if (emailMatch || companyMatch) {
    return {
      isKnown: true,
      personName: "Homa",
      companyName: "Draper Fence & Rail",
      hasAppointment: true,
      appointmentNote:
        "📅 You have an appointment with our Senior Growth Consultant Rob at 11 AM to discuss next steps on the proposal.",
      exitContext:
        "Based on our prior conversation, we know exit readiness is a priority for you — so we've weighted your results with that lens. The numbers below reflect what a buyer would actually see today.",
    };
  }

  return { isKnown: false };
}

// ─── QUESTIONS ────────────────────────────────────────────────────────────────

export const SECTIONS: Section[] = [
  {
    id: "sales-process",
    phase: 1,
    title: "Sales Process",
    subtitle: "How structured & consistent is your selling system?",
    questions: [
      {
        id: "defined-process",
        text: "Do you have a defined, milestone-based sales process your team follows?",
        context: "From first contact to signed contract — is it documented and repeatable?",
        labels: ["No process", "Fully defined"],
      },
      {
        id: "contact-speed",
        text: "Do you contact new leads within 5 minutes or less?",
        context: "Speed-to-lead is one of the highest-ROI changes a contractor can make.",
        labels: ["Rarely", "Always"],
      },
      {
        id: "onspot-estimates",
        text: "What % of estimates do you deliver on-the-spot during the first visit?",
        context: "On-spot estimates close at 2–3× the rate of follow-up quotes.",
        labels: ["Very few", "Most of them"],
      },
      {
        id: "close-tracking",
        text: "Are you actively tracking your close rate by salesperson?",
        context: "You can't improve what you don't measure.",
        labels: ["Not tracking", "Full visibility"],
      },
    ],
  },
  {
    id: "team-performance",
    phase: 1,
    title: "Team Performance",
    subtitle: "How well is your sales team generating & converting business?",
    questions: [
      {
        id: "self-generated",
        text: "What % of business is self-generated by your reps (vs. inbound leads)?",
        context: "Proactive reps = predictable pipeline. Inbound-only = revenue volatility.",
        labels: ["All inbound", "Mostly self-gen"],
      },
      {
        id: "neighborhood-marketing",
        text: "Does your team systematically market every jobsite and neighborhood?",
        context: "Canvassing near every installed job is one of the highest-ROI activities in this trade.",
        labels: ["Never", "Always"],
      },
      {
        id: "addons",
        text: "What % of your orders include add-ons or upgrades?",
        context: "50%+ of jobs should include at least one upgrade — gates, premium materials, specialty installs.",
        labels: ["Rarely", "Most jobs"],
      },
    ],
  },
  {
    id: "people-systems",
    phase: 2,
    title: "People & Systems",
    subtitle: "How well do you hire, onboard, and retain salespeople?",
    questions: [
      {
        id: "hiring-vsl",
        text: "Do you have a structured hiring process with a pre-screen video or VSL?",
        context: "A-players evaluate YOU before they apply. A hiring VSL pre-qualifies candidates.",
        labels: ["No process", "Fully built"],
      },
      {
        id: "onboarding",
        text: "Do you have a documented onboarding playbook and 30/60/90-day schedule?",
        context: "70% of reps fail in 6 months — almost entirely because of zero onboarding structure.",
        labels: ["Sink or swim", "Full playbook"],
      },
      {
        id: "screening",
        text: "Do you use a behavioral or sales aptitude assessment when hiring?",
        context: "Screening for coachability and competitive drive vs. just résumé experience.",
        labels: ["Not using", "Always screen"],
      },
      {
        id: "employment-agreement",
        text: "Do you have a formal Sales Role Employment Agreement in place?",
        context: "Covers territory, commission, expectations, and non-solicitation.",
        labels: ["Handshake deal", "Formal agreement"],
      },
    ],
  },
  {
    id: "coaching-accountability",
    phase: 2,
    title: "Coaching & Accountability",
    subtitle: "How consistently does your team train, practice, and improve?",
    questions: [
      {
        id: "ride-alongs",
        text: "Do you conduct weekly virtual or in-person ride-alongs with your reps?",
        context: "The fastest way to identify and close skill gaps is live observation.",
        labels: ["Never", "Every week"],
      },
      {
        id: "role-play",
        text: "Does your team role-play sales scenarios at least weekly?",
        context: "Elite performers practice more than average ones — not less.",
        labels: ["Never", "Weekly"],
      },
      {
        id: "pipeline-followup",
        text: "Does your team follow up with every pipeline lead at least once per week?",
        context: "80% of sales require 5+ follow-ups. Most reps stop at 1–2.",
        labels: ["Inconsistent", "Always"],
      },
      {
        id: "kpis",
        text: "Are you measuring and reviewing KPIs with your team on a regular cadence?",
        context: "Appointments set, close rate, average ticket, follow-up rate — reviewed weekly.",
        labels: ["Not measured", "Full dashboard"],
      },
    ],
  },
  {
    id: "valuation-readiness",
    phase: 3,
    title: "Exit & Valuation Readiness",
    subtitle: "How transferable and scalable is your sales operation?",
    questions: [
      {
        id: "referral-program",
        text: "Do you have a formal referral program your team actively promotes?",
        context: "Referral revenue is the highest-margin, most predictable revenue a contractor can have.",
        labels: ["No program", "Active program"],
      },
      {
        id: "owner-dependency",
        text: "How owner-independent is your sales operation on a daily basis?",
        context: "Can your team generate and close business without you in the room?",
        labels: ["I close everything", "Runs without me"],
      },
      {
        id: "documented-playbook",
        text: "Is your complete sales process documented in a written playbook?",
        context: "Buyers pay a 2×+ multiple premium for businesses where the process outlives the owner.",
        labels: ["In my head only", "Fully documented"],
      },
      {
        id: "revenue-predictability",
        text: "How predictable is your revenue month-to-month?",
        context: "Revenue that swings 40%+ monthly is a valuation killer with PE and strategic buyers.",
        labels: ["Very volatile", "Very predictable"],
      },
    ],
  },
];

export const TOTAL_QUESTIONS = SECTIONS.reduce((a, s) => a + s.questions.length, 0);
export const MAX_SCORE = TOTAL_QUESTIONS * 5;

// ─── DIMENSION SCORES ────────────────────────────────────────────────────────
// Each dimension is a 0–100 percentage derived purely from the answers.

export type Dimensions = {
  process: number;     // Sales process maturity
  team: number;        // Team self-generation & output
  people: number;      // Hiring / onboarding systems
  coaching: number;    // Accountability & coaching cadence
  valuation: number;   // Exit / owner-independence readiness
  overall: number;     // Weighted composite
};

export function computeDimensions(scores: Scores): Dimensions {
  const pct = (keys: string[]) => {
    const total = keys.reduce((a, k) => a + (scores[k] ?? 0), 0);
    return Math.round((total / (keys.length * 5)) * 100);
  };

  const process   = pct(["defined-process", "contact-speed", "onspot-estimates", "close-tracking"]);
  const team      = pct(["self-generated", "neighborhood-marketing", "addons"]);
  const people    = pct(["hiring-vsl", "onboarding", "screening", "employment-agreement"]);
  const coaching  = pct(["ride-alongs", "role-play", "pipeline-followup", "kpis"]);
  const valuation = pct(["referral-program", "owner-dependency", "documented-playbook", "revenue-predictability"]);

  // Weighted composite: valuation & process weighted slightly higher
  const overall = Math.round(
    process * 0.22 +
    team * 0.18 +
    people * 0.18 +
    coaching * 0.18 +
    valuation * 0.24
  );

  return { process, team, people, coaching, valuation, overall };
}

// ─── SEGMENTATION ENGINE ─────────────────────────────────────────────────────
// Decision tree based purely on dimension scores.
// No names, no hardcoded companies — identity overlay is separate.

export function classifySegment(scores: Scores): SegmentResult {
  const d = computeDimensions(scores);

  // ── Segment 1: Exit-Ready Builder ──────────────────────────────────────────
  // Low valuation readiness + moderate-to-decent overall = knows the business,
  // hasn't built the infrastructure a buyer needs to see.
  if (d.valuation <= 45 && d.overall < 68) {
    const ownerDep   = scores["owner-dependency"]    ?? 0;
    const playbook   = scores["documented-playbook"] ?? 0;
    const revPred    = scores["revenue-predictability"] ?? 0;
    const referral   = scores["referral-program"]    ?? 0;

    // Granular sub-flavors within Exit-Ready Builder
    const deepOwnerDep = ownerDep <= 2;
    const noPlaybook   = playbook <= 2;
    const volatileRev  = revPred <= 2;
    const noReferral   = referral <= 2;

    const gaps: string[] = [];
    if (deepOwnerDep) gaps.push("owner dependency");
    if (noPlaybook)   gaps.push("undocumented process");
    if (volatileRev)  gaps.push("revenue volatility");
    if (noReferral)   gaps.push("no referral engine");

    const primaryGap = gaps[0] ?? "valuation infrastructure";

    const descriptionVariants: Record<string, string> = {
      "owner dependency":
        "The business runs because you run it. Customers trust you specifically. Deals close because you're in the room. That's genuinely impressive — and it's also the single variable that will compress your exit multiple the most. Buyers don't pay full price for a business that leaves with the owner.",
      "undocumented process":
        "Your sales instincts are sharp — the problem is they live entirely in your head. There's no written playbook, no documented process, no system a new hire can follow on day one. That makes the business hard to scale and even harder to sell at the multiple it deserves.",
      "revenue volatility":
        "Month-to-month revenue swings are one of the first things a sophisticated buyer will flag in due diligence. Predictable, recurring-ish revenue gets priced at a premium. Volatile revenue gets discounted — even if the annual number looks strong.",
      "no referral engine":
        "Referral revenue is the highest-margin, most defensible revenue a specialty contractor can show a buyer. Without a structured referral program, you're leaving both money and multiple on the table every single month.",
      "valuation infrastructure":
        "The operational foundation is solid — but the systems a buyer needs to see aren't visible yet. Sales infrastructure, documented processes, and predictable pipelines are what move the needle from a 4× to a 7× multiple.",
    };

    const opportunityVariants: Record<string, string[]> = {
      "owner dependency": [
        "Shift from 'I close deals' to 'my process closes deals' — document every step so it works without you",
        "Track close rate by rep separately from your own — make the gap visible so you can close it",
        "Build a referral engine that generates pipeline your team can own and work independently",
        "Reduce owner-mention rate in reviews: from 'the owner handled it' to 'the team handled it'",
      ],
      "undocumented process": [
        "Build a written sales playbook — even a basic one raises valuation and accelerates onboarding",
        "Document your best 3 objection responses so any rep can handle them, not just you",
        "Create a follow-up cadence template so nothing falls through the cracks when you're not watching",
        "Set up KPI tracking — even a simple spreadsheet — so you can show a buyer a trend line",
      ],
      "revenue volatility": [
        "Install a weekly pipeline review cadence so you see revenue problems 4–6 weeks before they hit",
        "Build a referral program to create a second, more consistent pipeline layer",
        "Create a seasonal follow-up system so slow months have active pipeline being worked",
        "Track close rate monthly — even small improvements compound fast into more predictable revenue",
      ],
      "no referral engine": [
        "Build a simple referral ask into every job completion — most contractors close 30%+ of referrals",
        "Create a neighborhood canvassing system so every job generates 3–5 new opportunities",
        "Develop a past-customer follow-up sequence — past buyers are your highest-converting leads",
        "Add a referral incentive to your sales role agreements so reps are rewarded for generating them",
      ],
      "valuation infrastructure": [
        "Document your complete sales process — this is the #1 thing buyers look for in due diligence",
        "Install measurable KPIs so you can show a buyer 12+ months of improving performance data",
        "Build a referral engine to make revenue more predictable and defensible",
        "Reduce owner dependency in every part of the sales cycle — each step you remove adds multiple",
      ],
    };

    const insightVariants: Record<string, string> = {
      "owner dependency":
        `Specialty contractors with documented, owner-independent sales systems sell for 6–9× EBITDA. Owner-dependent businesses typically price at 3–5×. On a business doing $2M revenue with 12% EBITDA, that gap is $480K–$960K in exit value — sitting idle right now.`,
      "undocumented process":
        `Buyers pay a 2× multiple premium when processes are fully documented. It's not about whether the business performs — it's about whether it performs without the founder. Documented systems signal that the business is transferable. That's what moves the number.`,
      "revenue volatility":
        `Revenue swings of 40%+ month-to-month reduce EBITDA multiples by 1–2× in most specialty contractor transactions. Buyers model risk — and volatility is priced as risk. A 12-month trend of tightening variance can literally add six figures to your sale price.`,
      "no referral engine":
        `Referral revenue closes at 3× the rate of cold leads and costs almost nothing to generate. Contractors with active referral programs show buyers a defensible, low-cost growth channel — which is worth more at exit than equivalent cold-lead revenue.`,
      "valuation infrastructure":
        `The gap between a 4.5× and a 6.5× multiple isn't usually revenue — it's documentation, systems, and owner independence. On a $2M EBITDA business, closing that gap is worth $4M. Most of the work to get there takes 12–18 months to install and demonstrate.`,
    };

    return {
      primary: "Exit-Ready Builder",
      secondary: "Valuation Gap",
      emoji: "🎯",
      color: "#00D9FF",
      tagline: `You're building something valuable — buyers just can't see it yet.`,
      description: descriptionVariants[primaryGap],
      strengths: buildStrengths(d, scores),
      opportunities: opportunityVariants[primaryGap],
      insight: insightVariants[primaryGap],
      urgency: buildUrgency(d, "exit"),
    };
  }

  // ── Segment 2: Exhausted Scaler ─────────────────────────────────────────────
  // Low process + owner doing most of the selling + moderate team score
  if (d.process <= 45 && d.overall < 60) {
    const ownerDep = scores["owner-dependency"] ?? 0;
    const closeTrk = scores["close-tracking"]   ?? 0;
    const defined  = scores["defined-process"]  ?? 0;

    const noData       = closeTrk <= 2;
    const noProcess    = defined <= 2;
    const ownerSelling = ownerDep <= 2;

    const primaryFlavor = ownerSelling ? "owner-selling"
      : noProcess ? "no-process"
      : noData    ? "no-data"
      : "default";

    const descriptions: Record<string, string> = {
      "owner-selling":
        "Your instincts close deals your team can't replicate. You know it, they know it, and every customer who asks for you by name confirms it. That's not a compliment — it's a ceiling. The business can only grow as fast as you can personally show up, estimate, and follow up.",
      "no-process":
        "Every rep is improvising. Some are better at it than others, which means your results are wildly inconsistent depending on who picks up the lead. You can't coach what isn't written down, and you can't scale what only exists in someone's head.",
      "no-data":
        "You're flying without instruments. You probably have a gut sense for who your best rep is — but no data to back it up, no close rate by person, no follow-up rate, no accountability dashboard. The reps who are quietly losing deals are invisible until it's too late.",
      "default":
        "The sales operation runs — just not consistently. Some weeks are strong, some aren't, and the difference usually comes down to who's having a good week rather than the system working reliably.",
    };

    const opportunities: Record<string, string[]> = {
      "owner-selling": [
        "Codify YOUR selling approach into a written process anyone can follow — this is the highest-leverage thing you can do",
        "Set a 90-day goal: have your best rep close their first deal completely without you in the room",
        "Start measuring close rate per rep so the gaps are visible, not just felt",
        "Build a structured follow-up system so leads don't die when you're not the one working them",
      ],
      "no-process": [
        "Document the 5 steps every sale goes through — even rough notes beat no notes",
        "Create a standard estimate template so every rep presents value the same way",
        "Build a 3-touch follow-up sequence and make it non-negotiable for every open quote",
        "Run one weekly team meeting focused only on pipeline — what's open, what's stuck, what's closing",
      ],
      "no-data": [
        "Start tracking close rate per rep this week — even a simple spreadsheet changes behavior",
        "Measure lead response time — the fastest-responding contractor wins 40%+ of the time",
        "Create a weekly KPI review so every rep knows their numbers before Friday",
        "Use your data to identify your #1 bottleneck — is it leads, close rate, or follow-up failure?",
      ],
      "default": [
        "Define your sales process end-to-end so consistency is the default, not the exception",
        "Install a weekly accountability cadence so performance gaps are visible in real time",
        "Measure and share close rate data with the team — transparency drives improvement",
        "Build a follow-up system so no quote goes more than 72 hours without a touch",
      ],
    };

    return {
      primary: "Exhausted Scaler",
      secondary: "Process Gap",
      emoji: "⚡",
      color: "#FF6B35",
      tagline: "You're the ceiling. The business can only scale as far as you can personally reach.",
      description: descriptions[primaryFlavor],
      strengths: buildStrengths(d, scores),
      opportunities: opportunities[primaryFlavor],
      insight:
        "Most contractors at this stage aren't close-rate problems — they're follow-up problems. 80% of closed deals happen after the 5th contact. The average contractor rep stops at 1–2. Closing that gap alone — without changing anything else — typically moves revenue 15–25% in 90 days.",
      urgency: buildUrgency(d, "scale"),
    };
  }

  // ── Segment 3: Attrition Risk ────────────────────────────────────────────────
  // Low people + low coaching = revolving door problem
  if (d.people <= 40 && d.coaching <= 45) {
    const onboarding = scores["onboarding"]  ?? 0;
    const rolePlay   = scores["role-play"]   ?? 0;
    const rideAlongs = scores["ride-alongs"] ?? 0;

    const noOnboarding = onboarding <= 2;
    const noCoaching   = rolePlay <= 2 && rideAlongs <= 2;

    const flavor = noOnboarding ? "no-onboarding"
      : noCoaching   ? "no-coaching"
      : "default";

    const descriptions: Record<string, string> = {
      "no-onboarding":
        "You hire based on energy and experience, throw them in the field, and hope they figure it out. Some do. Most don't. The ones who leave take their pipeline with them — and 4–6 months of your time and recruiting costs go with them. The industry average rep tenure without onboarding structure is 5 months.",
      "no-coaching":
        "Your team has never been through a real role-play. They've never had a manager sit with them on a live call or ride-along and debrief what happened. That means every mistake they make is invisible — and every mistake costs you a deal. Skills plateau when there's no practice structure.",
      "default":
        "The infrastructure to develop and retain great salespeople isn't in place yet. When good people leave — and they will — the knowledge walks out with them. The fix isn't paying more. It's building the system that makes people want to stay and grow.",
    };

    return {
      primary: "Attrition Risk",
      secondary: "People Infrastructure Gap",
      emoji: "🔄",
      color: "#f97316",
      tagline: "Your best hire is one resignation away from your biggest problem.",
      description: descriptions[flavor],
      strengths: buildStrengths(d, scores),
      opportunities: [
        "Build a 30/60/90-day onboarding track — this single change reduces first-year turnover by 50%+",
        "Implement weekly ride-alongs or recorded call reviews so coaching is systematic, not reactive",
        "Add a behavioral screening step to your hiring process before you make the next offer",
        "Create a formal Sales Role Agreement so expectations are set in writing before day one",
        "Run monthly role-plays on your 3 most common objections — practice in a safe environment beats learning on live prospects",
      ],
      insight:
        "70% of sales reps fail in the first 6 months — almost always because of onboarding failure, not talent failure. The rep isn't usually the problem. The system is. Contractors who fix this see rep ramp time drop from 4–6 months to 6–8 weeks.",
      urgency: buildUrgency(d, "people"),
    };
  }

  // ── Segment 4: Growth-Stalled ────────────────────────────────────────────────
  // Mid scores across the board — decent but not breaking through
  if (d.overall >= 40 && d.overall < 65) {
    const lowestDimension = getLowestDimension(d);

    const bottleneckInsights: Record<string, string> = {
      process:
        "Your process score is the drag. You have people and some accountability in place — the ceiling is that your sales steps aren't standardized enough to deliver consistent results across every rep.",
      team:
        "Your team is running mostly on inbound. That means your revenue is downstream of your marketing — and when leads slow down, so does everything else. Self-generated pipeline is the lever that breaks that dependency.",
      people:
        "You've got process and some accountability — but the people infrastructure (hiring, onboarding, retention) is the missing link. One good hire who churns because there was no ramp structure is an expensive lesson.",
      coaching:
        "The sales cadence and review structure is the gap. You can see what needs to improve — but without weekly coaching and accountability, the needle doesn't move fast enough.",
      valuation:
        "Everything else is moving — but the valuation infrastructure isn't in place. A buyer looking at your business today would see a revenue story, not a system story. That distinction matters when it's time to negotiate a multiple.",
    };

    return {
      primary: "Growth-Stalled",
      secondary: "Ceiling Without a Catalyst",
      emoji: "📈",
      color: "#eab308",
      tagline: "Solid foundation. The ceiling is infrastructure, not effort.",
      description:
        "Revenue is real. Reputation is real. The team is functional. What's missing is the layer of system that takes 'working hard' and converts it into 'scaling reliably.' The business has outgrown hustle as a strategy — and hasn't yet installed what replaces it.",
      strengths: buildStrengths(d, scores),
      opportunities: buildOpportunitiesFromLowest(d, scores),
      insight: bottleneckInsights[lowestDimension],
      urgency: buildUrgency(d, "stalled"),
    };
  }

  // ── Segment 5: Scale-Ready ───────────────────────────────────────────────────
  // High overall — optimizing, not building from scratch
  if (d.overall >= 65) {
    const nearExit = d.valuation >= 65;

    return {
      primary: "Scale-Ready",
      secondary: nearExit ? "Exit Optimization Phase" : "Performance Optimization Phase",
      emoji: "🚀",
      color: "#22c55e",
      tagline: nearExit
        ? "Strong foundation. Time to maximize your exit multiple."
        : "Strong foundation. Time to compound what's working.",
      description: nearExit
        ? "You're ahead of 85% of contractors in your space. The infrastructure is there — now it's about making sure everything is documented well enough that a buyer sees a machine, not a team. The difference between your current trajectory and a premium exit multiple is narrower than you think — and mostly about consistency documentation."
        : "The infrastructure is genuinely in place. Your scores reflect a business that's built to perform — not just hustle. The opportunity from here isn't fixing what's broken. It's compounding what's working and filling the specific gaps that are still holding back ceiling-level performance.",
      strengths: buildStrengths(d, scores),
      opportunities: buildOpportunitiesFromLowest(d, scores),
      insight: nearExit
        ? "At this maturity level, a 10% improvement in close rate or average ticket adds disproportionate bottom-line impact — and that compounds directly into exit valuation. Buyers pay full price for businesses that are already performing like a system."
        : "The gap between a strong business and an elite one is usually found in the 20% of metrics that don't get tracked. Your next breakthrough is in the data you're not measuring yet.",
      urgency: buildUrgency(d, "scale-ready"),
    };
  }

  // ── Fallback ─────────────────────────────────────────────────────────────────
  return {
    primary: "Early Stage",
    secondary: "Foundation Building",
    emoji: "🔧",
    color: "#eab308",
    tagline: "Every elite sales operation started exactly here.",
    description:
      "The scoring suggests a sales operation in early stages — which means the upside is enormous. The contractors who systematize early get a permanent competitive advantage over those who wait until they're forced to.",
    strengths: buildStrengths(d, scores),
    opportunities: [
      "Define your sales process end-to-end before adding more people",
      "Start measuring close rate and lead response time this week",
      "Build a simple onboarding guide for your first or next hire",
      "Create a follow-up cadence and make it non-negotiable",
    ],
    insight:
      "The ROI on installing sales infrastructure early — before you're dependent on it — is 10× higher than fixing it under pressure. Most contractors wait too long.",
    urgency: buildUrgency(d, "early"),
  };
}

// ─── DYNAMIC STRENGTHS BUILDER ───────────────────────────────────────────────
// Generates strengths list from actual high-scoring dimensions, not assumptions.

function buildStrengths(d: Dimensions, scores: Scores): string[] {
  const strengths: string[] = [];

  if (d.process >= 60)
    strengths.push("Your sales process has real structure — that's ahead of most contractors at your stage");
  if (d.team >= 60)
    strengths.push("Your team is generating business proactively, not just waiting for inbound");
  if (d.people >= 60)
    strengths.push("You've invested in hiring and onboarding infrastructure — reps have a real chance to succeed");
  if (d.coaching >= 60)
    strengths.push("Regular coaching and accountability cadences are in place — that's a genuine differentiator");
  if (d.valuation >= 60)
    strengths.push("Your valuation readiness is strong — the business has the bones a buyer wants to see");
  if ((scores["owner-dependency"] ?? 0) >= 4)
    strengths.push("Your sales operation can run without you in the room — that alone is worth a premium multiple");
  if ((scores["referral-program"] ?? 0) >= 4)
    strengths.push("Active referral program generating high-margin, predictable pipeline");
  if ((scores["onspot-estimates"] ?? 0) >= 4)
    strengths.push("On-spot estimates close 2–3× faster than follow-up quotes — you're already doing this");
  if ((scores["contact-speed"] ?? 0) >= 4)
    strengths.push("Fast lead response time — this alone puts you ahead of 60% of contractors");

  // Always have at least 2 strengths (floor)
  if (strengths.length === 0) {
    strengths.push("You're asking the right questions — most contractors never audit their sales operation at all");
    strengths.push("Taking this assessment is the first step most competitors will never take");
  } else if (strengths.length === 1) {
    strengths.push("You've built a real business with real customers — that foundation is what systems plug into");
  }

  return strengths.slice(0, 5);
}

// ─── DYNAMIC URGENCY BUILDER ─────────────────────────────────────────────────

function buildUrgency(d: Dimensions, context: string): string {
  const urgencyMap: Record<string, string> = {
    exit:
      "If exit is on your horizon in the next 2–3 years, the window to install and demonstrate these systems is right now. Buyers want to see 12–18 months of owner-independent performance before they sign. Every month you wait is a month that clock doesn't start.",
    scale:
      "Every month without a documented process is a month your team is losing deals you'd have closed yourself. The compounding cost of that gap — in closed deals, rep turnover, and missed pipeline — adds up faster than most owners realize.",
    people:
      "One key resignation from your current team resets the clock. The cost of a single bad hire or unplanned departure — recruiting, lost pipeline, retraining — runs $40K–$80K in most specialty contracting businesses. Systems are insurance.",
    stalled:
      "The businesses that break through plateaus aren't the ones that work harder — they're the ones that install the right infrastructure at the right time. The window to do that before your competitors do is shorter than it feels.",
    "scale-ready":
      "The gap between your current trajectory and a premium exit is mostly documentation and coaching consistency — both of which compound fast. Businesses at this stage who optimize aggressively in the next 12 months are the ones that set the ceiling for everyone else.",
    early:
      "The contractors who install sales infrastructure early — before they're forced to — get a permanent advantage over those who wait. The time to build the system is when you have the bandwidth to do it right.",
  };

  return urgencyMap[context] ?? urgencyMap["stalled"];
}

// ─── LOWEST DIMENSION FINDER ─────────────────────────────────────────────────

function getLowestDimension(d: Dimensions): keyof Omit<Dimensions, "overall"> {
  const dims = { process: d.process, team: d.team, people: d.people, coaching: d.coaching, valuation: d.valuation };
  return (Object.entries(dims).sort((a, b) => a[1] - b[1])[0][0]) as keyof typeof dims;
}

// ─── OPPORTUNITIES FROM LOWEST DIMENSION ────────────────────────────────────

function buildOpportunitiesFromLowest(d: Dimensions, scores: Scores): string[] {
  const lowest = getLowestDimension(d);

  const opps: Record<string, string[]> = {
    process: [
      "Document your top 5 sales steps so every rep runs the same play, every time",
      "Install a lead response SLA — first contact within 5 minutes is the benchmark that wins",
      "Build an on-spot estimate template so deals close same-day, not 3 follow-ups later",
      "Create a weekly close-rate review — visibility drives accountability",
    ],
    team: [
      "Launch a neighborhood canvassing system — every installed job should generate 3–5 new conversations",
      "Build a self-gen expectation into every rep's role — inbound-only reps are a revenue liability",
      "Add a structured upgrade ask to every estimate — 50%+ of jobs should include at least one add-on",
      "Create a referral ask template for job completion so referrals happen systematically, not by luck",
    ],
    people: [
      "Build a 30/60/90-day onboarding track so new hires ramp in weeks, not months",
      "Add a behavioral screening step before your next hire — coachability beats experience",
      "Create a Sales Role Agreement template covering territory, commission, and non-solicitation",
      "Build a hiring VSL so A-players know they're applying to a professional operation",
    ],
    coaching: [
      "Launch weekly 30-min ride-alongs or recorded call reviews — live observation accelerates improvement faster than anything else",
      "Run monthly role-plays on your top 3 objections so reps have practiced answers, not improvised ones",
      "Build a pipeline review cadence so every lead is visible and nothing stalls without a reason",
      "Create a KPI dashboard — close rate, lead response time, follow-up rate — reviewed every week",
    ],
    valuation: [
      "Document your complete sales process — this is the #1 thing buyers look for in due diligence",
      "Build a referral program to show buyers a second, defensible pipeline channel",
      "Reduce owner involvement in sales decisions — every step you remove adds to the multiple",
      "Track and present 12+ months of KPI data so a buyer sees a trend, not a snapshot",
    ],
  };

  return opps[lowest] ?? opps["process"];
}

// ─── TEASER TEXT ENGINE ──────────────────────────────────────────────────────
// Generates a blurred-result teaser based on answers — specific enough to feel
// accurate, but not enough to give away the full report.

export function getTeaserText(scores: Scores): string {
  const d = computeDimensions(scores);

  const ownerDep  = scores["owner-dependency"]     ?? 0;
  const playbook  = scores["documented-playbook"]  ?? 0;
  const revPred   = scores["revenue-predictability"] ?? 0;
  const closeTrack = scores["close-tracking"]      ?? 0;
  const onboarding = scores["onboarding"]          ?? 0;
  const rideAlongs = scores["ride-alongs"]         ?? 0;

  // Exit-specific insight — answer-driven, no identity
  if (d.valuation <= 35 && ownerDep <= 2 && playbook <= 2) {
    return `Your valuation dimension scored in the bottom quartile — specifically around owner dependency and documented process. These are the two variables that most directly compress exit multiples for specialty contractors. There's a specific dollar figure attached to that gap. Your full report breaks it down.`;
  }

  if (d.valuation <= 45 && revPred <= 2) {
    return `Your revenue predictability score is flagging a pattern that sophisticated buyers price as risk. Month-to-month volatility reduces EBITDA multiples by 1–2× in most specialty contractor transactions — even when the annual number looks healthy. Your full report shows the fix.`;
  }

  if (d.process <= 35 && ownerDep <= 2) {
    return `Your scores are showing a pattern we see constantly in high-performing owner-operators: the process lives in your head, not on paper. The business performs because you perform. Your full report quantifies exactly what that's costing you — and what it takes to change it.`;
  }

  if (d.people <= 35 && onboarding <= 2) {
    return `Your people-systems score suggests your hiring and onboarding infrastructure hasn't kept pace with your ambitions for the team. The stat that usually surprises people here: 70% of rep failures are onboarding failures — not talent failures. Your full report shows where the gap is.`;
  }

  if (d.coaching <= 35 && rideAlongs <= 2) {
    return `Your coaching and accountability score revealed something specific: the reps are practicing on live prospects instead of in structured training. That's where deals are being lost invisibly — not in the field, but in the prep. Your full report identifies the highest-leverage fix.`;
  }

  if (closeTrack <= 2) {
    return `You're running the business without one of the most important instruments in sales: close rate by rep. Without that number, you can't tell who's quietly losing deals, who's your highest leveraged performer, or where coaching should be focused. Your full report shows what that visibility unlocks.`;
  }

  if (d.overall >= 70) {
    return `Your overall score puts you ahead of most contractors in this space. Your full report identifies the specific 2–3 gaps between where you are and peak performance — because at this stage, it's optimization, not rebuilding.`;
  }

  return `Your scorecard reveals a specific pattern across 5 dimensions — with clear gaps between your current trajectory and where the highest-performing contractors in this trade are operating. Your full report shows exactly where those gaps are, and what each one is worth to fix.`;
}

// ─── HELPERS ─────────────────────────────────────────────────────────────────

export function scoreColor(pct: number): string {
  if (pct >= 80) return "#22c55e";
  if (pct >= 60) return "#00D9FF";
  if (pct >= 40) return "#eab308";
  if (pct >= 20) return "#f97316";
  return "#ef4444";
}

export function scoreLabel(pct: number): string {
  if (pct >= 80) return "Strong";
  if (pct >= 60) return "Developing";
  if (pct >= 40) return "Needs Work";
  if (pct >= 20) return "At Risk";
  return "Critical Gap";
}

export function formatPhone(value: string): string {
  const digits = value.replace(/\D/g, "").substring(0, 10);
  if (digits.length === 0) return "";
  if (digits.length <= 3) return `(${digits}`;
  if (digits.length <= 6) return `(${digits.slice(0, 3)}) ${digits.slice(3)}`;
  return `(${digits.slice(0, 3)}) ${digits.slice(3, 6)}-${digits.slice(6)}`;
}

export function isValidPhone(phone: string): boolean {
  const digits = phone.replace(/\D/g, "");
  if (digits.length !== 10) return false;
  if (digits[0] === "0" || digits[0] === "1") return false;
  if (/^(\d)\1{9}$/.test(digits)) return false;
  const fakeNumbers = ["1234567890", "0987654321", "1111111111", "2222222222",
    "3333333333", "4444444444", "5555555555", "6666666666", "7777777777",
    "8888888888", "9999999999", "1231231234", "0000000000"];
  if (fakeNumbers.includes(digits)) return false;
  return true;
}

export function isValidEmail(email: string): boolean {
  if (!/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(email)) return false;
  // Block obvious fake/placeholder domains
  const fakeDomains = ["test.com", "example.com", "fake.com", "temp.com",
    "noreply.com", "mailinator.com", "guerrillamail.com", "throwaway.com"];
  const domain = email.split("@")[1]?.toLowerCase();
  if (domain && fakeDomains.includes(domain)) return false;
  return true;
}
