// STG Scorecard Data & Types

export type Scores = Record<string, number>;

export type Section = {
  id: string;
  phase: number;
  title: string;
  subtitle: string;
  questions: Question[];
};

export type Question = {
  id: string;
  text: string;
  context?: string;
  labels: [string, string];
};

export type SegmentResult = {
  primary: string;
  secondary: string;
  emoji: string;
  color: string;
  tagline: string;
  description: string;
  strengths: string[];
  opportunities: string[];
  insight: string;
  urgency: string;
};

export const SECTIONS: Section[] = [
  {
    id: "sales-process",
    phase: 1,
    title: "Sales Process",
    subtitle: "How structured & consistent is your selling system?",
    questions: [
      {
        id: "defined-process",
        text: "Do you have a defined, milestone-based sales process your team follows?",
        context: "From first contact to signed contract — is it documented and repeatable?",
        labels: ["No process", "Fully defined"],
      },
      {
        id: "contact-speed",
        text: "Do you contact new leads within 5 minutes or less?",
        context: "Speed-to-lead is one of the highest-ROI changes a contractor can make.",
        labels: ["Rarely", "Always"],
      },
      {
        id: "onspot-estimates",
        text: "What % of estimates do you deliver on-the-spot during the first visit?",
        context: "On-spot estimates close at 2–3× the rate of follow-up quotes.",
        labels: ["Very few", "Most of them"],
      },
      {
        id: "close-tracking",
        text: "Are you actively tracking your close rate by salesperson?",
        context: "You can't improve what you don't measure.",
        labels: ["Not tracking", "Full visibility"],
      },
    ],
  },
  {
    id: "team-performance",
    phase: 1,
    title: "Team Performance",
    subtitle: "How well is your sales team generating & converting business?",
    questions: [
      {
        id: "self-generated",
        text: "What % of business is self-generated by your reps (vs. inbound leads)?",
        context: "Proactive reps = predictable pipeline. Inbound-only = revenue volatility.",
        labels: ["All inbound", "Mostly self-gen"],
      },
      {
        id: "neighborhood-marketing",
        text: "Does your team systematically market every jobsite and neighborhood?",
        context: "Canvassing near every installed job is one of the highest-ROI marketing activities in fence/rail.",
        labels: ["Never", "Always"],
      },
      {
        id: "addons",
        text: "What % of your orders include add-ons or upgrades?",
        context: "50%+ of jobs should include at least one upgrade — gates, premium materials, railings, etc.",
        labels: ["Rarely", "Most jobs"],
      },
    ],
  },
  {
    id: "people-systems",
    phase: 2,
    title: "People & Systems",
    subtitle: "How well do you hire, onboard, and retain salespeople?",
    questions: [
      {
        id: "hiring-vsl",
        text: "Do you have a structured hiring process with a pre-screen video or VSL?",
        context: "The best A-players evaluate YOU before they apply. A hiring VSL pre-qualifies candidates.",
        labels: ["No process", "Fully built"],
      },
      {
        id: "onboarding",
        text: "Do you have a documented onboarding playbook and 30/60/90-day schedule?",
        context: "70% of reps fail in 6 months. A structured onboarding system changes that.",
        labels: ["Sink or swim", "Full playbook"],
      },
      {
        id: "screening",
        text: "Do you use a behavioral or sales aptitude assessment when hiring?",
        context: "Screening for coachability and competitive drive vs. just résumé experience.",
        labels: ["Not using", "Always screen"],
      },
      {
        id: "employment-agreement",
        text: "Do you have a formal Sales Role Employment Agreement in place?",
        context: "Covers territory, commission, expectations, and non-solicitation.",
        labels: ["Handshake deal", "Formal agreement"],
      },
    ],
  },
  {
    id: "coaching-accountability",
    phase: 2,
    title: "Coaching & Accountability",
    subtitle: "How consistently does your team train, practice, and improve?",
    questions: [
      {
        id: "ride-alongs",
        text: "Do you conduct weekly virtual or in-person ride-alongs with your reps?",
        context: "The fastest way to identify and close skill gaps is live observation.",
        labels: ["Never", "Every week"],
      },
      {
        id: "role-play",
        text: "Does your team role-play sales scenarios at least weekly?",
        context: "Elite performers practice more than average ones — not less.",
        labels: ["Never", "Weekly"],
      },
      {
        id: "pipeline-followup",
        text: "Does your team follow up with every pipeline lead at least once per week?",
        context: "80% of sales require 5+ follow-ups. Most reps stop at 1–2.",
        labels: ["Inconsistent", "Always"],
      },
      {
        id: "kpis",
        text: "Are you measuring and reviewing KPIs with your team on a regular cadence?",
        context: "Appointments set, close rate, average ticket, follow-up rate — measured weekly.",
        labels: ["Not measured", "Full dashboard"],
      },
    ],
  },
  {
    id: "valuation-readiness",
    phase: 3,
    title: "Exit & Valuation Readiness",
    subtitle: "How transferable and scalable is your sales operation?",
    questions: [
      {
        id: "referral-program",
        text: "Do you have a formal referral program your team actively promotes?",
        context: "Referral revenue is the highest-margin, most predictable revenue a contractor can have.",
        labels: ["No program", "Active program"],
      },
      {
        id: "owner-dependency",
        text: "How owner-independent is your sales operation on a daily basis?",
        context: "Can your team generate and close business without you in the room?",
        labels: ["I close everything", "Runs without me"],
      },
      {
        id: "documented-playbook",
        text: "Is your complete sales process documented in a written playbook?",
        context: "Buyers pay a 2×+ premium for businesses where the process outlives the owner.",
        labels: ["In my head only", "Fully documented"],
      },
      {
        id: "revenue-predictability",
        text: "How predictable is your revenue month-to-month?",
        context: "Revenue that swings 40%+ monthly is a valuation killer with PE buyers.",
        labels: ["Very volatile", "Very predictable"],
      },
    ],
  },
];

export const TOTAL_QUESTIONS = SECTIONS.reduce((a, s) => a + s.questions.length, 0);
export const MAX_SCORE = TOTAL_QUESTIONS * 5;

export function classifySegment(scores: Scores, total: number): SegmentResult {
  const pct = (total / MAX_SCORE) * 100;

  const valuationKeys = ["owner-dependency", "documented-playbook", "revenue-predictability", "referral-program"];
  const valuationScore = valuationKeys.reduce((a, k) => a + (scores[k] || 0), 0);

  const processKeys = ["defined-process", "contact-speed", "onspot-estimates", "close-tracking"];
  const processScore = processKeys.reduce((a, k) => a + (scores[k] || 0), 0);

  const peopleKeys = ["hiring-vsl", "onboarding", "screening", "employment-agreement"];
  const peopleScore = peopleKeys.reduce((a, k) => a + (scores[k] || 0), 0);

  const lowValuation = valuationScore <= 10;
  const lowProcess = processScore <= 10;
  const lowPeople = peopleScore <= 10;

  // Exit-Ready Builder (Homa's profile — building to sell, owner-dependent)
  if (lowValuation && pct < 65) {
    return {
      primary: "Exit-Ready Builder",
      secondary: "Valuation Gap",
      emoji: "🎯",
      color: "#00D9FF",
      tagline: "You're building something valuable — but buyers won't see it yet.",
      description:
        "You have a real business with real customers and a strong reputation — Draper Fence & Rail has been delivering exceptional work since 2014. The challenge: your sales operation is still wired to YOUR instincts, YOUR relationships, YOUR presence on every deal. That's worth less on paper than it is in reality. The good news? This gap is entirely fixable, and closing it adds serious dollars to an exit valuation.",
      strengths: [
        "Strong local reputation and loyal customer base in the Greater Indianapolis area",
        "Quality-first, no-subcontractor culture that PE buyers explicitly value",
        "Lifetime craftsmanship warranty — a differentiated, documentable competitive advantage",
        "Clear vision for growth and an exit timeline in the next 2–3 years",
        "Established operational infrastructure with 10+ years of delivery history",
      ],
      opportunities: [
        "Document your sales process so every estimate and follow-up happens systematically — not because you're watching",
        "Build a referral engine — the highest-margin, most predictable revenue stream a contractor can have",
        "Install measurable KPIs to show buyers a predictable, growing revenue story over 12–18 months",
        "Create a repeatable hiring & onboarding system before your next key hire so they ramp in 90 days, not 9 months",
        "Reduce owner-mention rate in reviews — move from 'Homa handled it' to 'the team handled it'",
      ],
      insight:
        "Specialty contractors with documented sales systems and owner-independent pipelines sell for 6–9× EBITDA. Without those systems, buyers price in your personal involvement as a risk — typically 3–4×. On a $2M fence & rail business with 10% EBITDA, that gap is $400K–$1M in exit value sitting on the table right now.",
      urgency:
        "If you want to exit in the next 2–3 years, the window to install these systems is right now. Buyers want to see 12–18 months of owner-independent performance before they sign. That clock starts the day you start building.",
    };
  }

  if (lowProcess && pct < 55) {
    return {
      primary: "Exhausted Scaler",
      secondary: "Process-Deficient",
      emoji: "⚡",
      color: "#FF6B35",
      tagline: "You're the best salesperson on your team. That's the problem.",
      description:
        "Your instincts close deals your team can't. You know it, they know it, and every customer who asks for you by name confirms it. That dependency is both your growth ceiling and a valuation killer.",
      strengths: [
        "Strong personal sales ability and deep customer trust",
        "Real revenue flowing through the business",
        "Market presence strong enough to attract new clients consistently",
      ],
      opportunities: [
        "Codify YOUR selling approach into a repeatable process anyone can follow",
        "Start measuring close rates and follow-up rates per rep",
        "Build a pre-call or on-site estimate system to accelerate deal velocity",
        "Create accountability structures that don't require your direct involvement",
      ],
      insight:
        "The fastest ROI in contractor sales isn't more marketing spend — it's closing 10–15 more percentage points of the leads you're already getting.",
      urgency:
        "Every month without a documented process is a month your team is losing deals you'd have closed yourself — and a month further from a premium exit multiple.",
    };
  }

  if (lowPeople && pct < 60) {
    return {
      primary: "Attrition Risk",
      secondary: "People-Systems Gap",
      emoji: "🔄",
      color: "#f97316",
      tagline: "Great people are hard to find. Even harder to keep without systems.",
      description:
        "You're running on the strength of individual people — not systems. When your best person walks out, so does their knowledge, their customer relationships, and their close rate.",
      strengths: [
        "You recognize the need for people infrastructure",
        "Existing team relationships are a real asset",
        "Quality delivery track record helps with retention",
      ],
      opportunities: [
        "Build a hiring process that finds coachable A-players, not just experienced ones",
        "Create a 30/60/90-day onboarding track so new people ramp fast",
        "Install a formal sales role agreement to set clear expectations",
        "Develop a behavioral screening process before making any hire",
      ],
      insight:
        "70% of sales reps fail in the first 6 months — almost entirely due to inadequate onboarding and zero process to follow. The rep isn't usually the problem. The system is.",
      urgency:
        "One key departure from your current team changes everything. Get systems in place before that happens.",
    };
  }

  if (pct >= 70) {
    return {
      primary: "Scale-Ready",
      secondary: "Optimization Phase",
      emoji: "🚀",
      color: "#22c55e",
      tagline: "Strong foundation. Time to optimize for a premium exit.",
      description:
        "You're ahead of most contractors in your space. The infrastructure is there — now it's about squeezing more performance out of what's working and making sure everything is fully documented for a future buyer.",
      strengths: [
        "Documented processes and accountability systems in place",
        "Measurable KPIs and pipeline visibility",
        "Team that can perform with less owner involvement",
        "Consistent revenue story that attracts premium buyers",
      ],
      opportunities: [
        "Layer in advanced coaching cadences to push top performers further",
        "Focus on valuation optimization — document everything buyers look for",
        "Expand add-on and upgrade revenue through systematic upselling",
        "Build out a referral engine to make revenue even more predictable",
      ],
      insight:
        "At this stage, a 10% improvement in close rate or average ticket adds disproportionate bottom-line value — and that compounds directly into exit valuation.",
      urgency:
        "The gap between a good exit and a great exit is narrower than you think — and mostly about documentation and coaching consistency.",
    };
  }

  return {
    primary: "Growth-Stalled",
    secondary: "Systems Gap",
    emoji: "📈",
    color: "#eab308",
    tagline: "You've built something real. The ceiling is your sales infrastructure.",
    description:
      "Revenue is there. Reputation is there. What's missing is the system that takes it to the next level — both in performance and in what a future buyer sees when they look under the hood.",
    strengths: [
      "Established market presence and customer base",
      "Core service quality that customers trust",
      "Demonstrated ability to generate consistent business",
    ],
    opportunities: [
      "Define and document your complete sales process end-to-end",
      "Build accountability systems around measurable KPIs",
      "Create a referral program to generate predictable, high-margin revenue",
      "Start reducing owner involvement in day-to-day sales decisions",
    ],
    insight:
      "Most contractors at this stage aren't far from a breakthrough. The missing piece is usually structure, not effort.",
    urgency:
      "Without systems, growth past the current ceiling requires more of YOU — not more leverage from a team.",
  };
}

export function scoreColor(pct: number): string {
  if (pct >= 80) return "#22c55e";
  if (pct >= 60) return "#00D9FF";
  if (pct >= 40) return "#eab308";
  if (pct >= 20) return "#f97316";
  return "#ef4444";
}

export function scoreLabel(pct: number): string {
  if (pct >= 80) return "Strong";
  if (pct >= 60) return "Developing";
  if (pct >= 40) return "Needs Work";
  if (pct >= 20) return "At Risk";
  return "Critical Gap";
}

export function formatPhone(value: string): string {
  const digits = value.replace(/\D/g, "").substring(0, 10);
  if (digits.length === 0) return "";
  if (digits.length <= 3) return `(${digits}`;
  if (digits.length <= 6) return `(${digits.slice(0, 3)}) ${digits.slice(3)}`;
  return `(${digits.slice(0, 3)}) ${digits.slice(3, 6)}-${digits.slice(6)}`;
}

export function isValidPhone(phone: string): boolean {
  const digits = phone.replace(/\D/g, "");
  if (digits.length !== 10) return false;
  if (digits[0] === "0" || digits[0] === "1") return false;
  if (/^(\d)\1{9}$/.test(digits)) return false;
  if (digits === "1234567890" || digits === "0987654321") return false;
  return true;
}

export function isValidEmail(email: string): boolean {
  return /^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(email);
}

export function getTeaserText(scores: Scores, segment: SegmentResult): string {
  const ownerDep = scores["owner-dependency"] || 0;
  const playbook = scores["documented-playbook"] || 0;
  const revPred = scores["revenue-predictability"] || 0;

  if (ownerDep <= 2 && playbook <= 2) {
    return "Your scores reveal significant owner dependency — which is the single variable that most impacts exit valuation in specialty contracting. There's a specific dollar figure attached to that gap, and your full report breaks it down.";
  }
  if (revPred <= 2) {
    return "Your revenue predictability score suggests month-to-month volatility that buyers typically discount. You're likely leaving real money on the table at exit — and the fix is more systematic than you'd expect.";
  }
  if (segment.primary === "Scale-Ready") {
    return "You're ahead of 80% of contractors in your space. Your full results reveal the specific optimization gaps between where you are and a premium exit multiple.";
  }
  return "Your scorecard reveals a specific pattern common in fence & specialty contractors who are building toward an exit — with a clear, addressable gap between current trajectory and maximum valuation. Your full report shows exactly where that gap lives.";
}
